stages:
  - package

# Publishes a tag/branch to Composer Packages of the current project
composer_package:

  image: curlimages/curl:latest

  tags:
    - docker

  rules:
    - if: $CI_COMMIT_TAG

  stage: package

  variables:
    URL: "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
  
  script:
    - VERSION=$(grep version composer.json | awk -F \" '{print $4}')
    - INSECURE=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
    - RESPONSE=$(curl -s -w "\n%{http_code}" $INSECURE --data tag=$CI_COMMIT_TAG $URL)
    - CODE=$(echo "$RESPONSE" | tail -n 1)
    - BODY=$(echo "$RESPONSE" | head -n 1)
    # Output state information
    - if [ $CODE -eq 201 ]; then
        echo "Package created - Code $CODE - $BODY";
      else
        echo "Could not create package - Code $CODE - $BODY";
        exit 1;
      fi
